services:
  app:
    build:
      context: .
    volumes:
      - $(pwd):/app
    ports:
      - "8000:8000"
    command: flask --app=app run --host=0.0.0.0 --port=8000 --reload
    environment:
      FLASK_APP: app.py